title: Analysis Scripts & Tutorials
description: Analysis scripts and tutorials for bioinformatics and computational biology

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  nav_pages:
    - scripts/tutorials/cutrun/index.md
    - scripts/tutorials/mini_lecture/index.md
